#!/usr/bin/env node
// Builds scripture-words.js: every 4–7 letter word in the Bible and the
// Book of Mormon (KJV and 1830-text data, pinned in tools/verify.mjs).
// Verse Word only accepts guesses from this list, the way real Wordle only
// accepts real words.  Run: node tools/build-words.mjs
// (tools/.scripture-cache is filled by running tools/verify.mjs once.)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = process.env.SCRIPTURE_CACHE || path.join(ROOT, 'tools', '.scripture-cache');
const files = fs.readdirSync(CACHE).filter(f => /(old-testament|new-testament|book-of-mormon)\.json$/.test(f));
if (files.length !== 3) throw new Error('Run node tools/verify.mjs once first, to download the scripture data');

const words = new Set();
for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(CACHE, f), 'utf8'));
  for (const b of data.books) for (const c of b.chapters) for (const v of c.verses) {
    for (const w of v.text.split(/[^A-Za-z]+/)) if (w.length >= 4 && w.length <= 7) words.add(w.toUpperCase());
  }
}
const list = [...words].sort();
fs.writeFileSync(path.join(ROOT, 'scripture-words.js'),
  '// Generated by tools/build-words.mjs: every 4–7 letter word in the Bible and the Book of Mormon.\n' +
  '// Verse Word accepts only these as guesses. Do not edit by hand.\n' +
  'window.SCRIPTURE_WORDS = "' + list.join(' ') + '";\n');
console.log(`scripture-words.js: ${list.length} words`);
